### PR TITLE
Add test script via package.json

### PR DESCRIPTION
**Pull request by sporto**
When trying to contribute to this library there is no instructions on how to test it. It requires me to install elm-test globally which I don't think should be necessary.

- This PR adds a `package.json` with a `test` script so you can run: `npm run test` to run the tests.
- Also adds instructions in the readme.

### CODE REVIEW

**Comment by sporto** [comment]
Also some tests are failing:

```
Running 82 tests. To reproduce these results, run: elm-test --fuzz 100 --seed 463149458

↓ CamelizeTest
↓ camelize
✗ It is the same lowercased string after removing the dashes and spaces

Given "\t"

    ""
    ╷
    │ Expect.equal
    ╵
    "\t"


Given "\n"

    ""
    ╷
    │ Expect.equal
    ╵
    "\n"


↓ HumanizeTest
↓ humanize
✗ It yields the same string after removing underscores, dashes and spaces

Given "\t"

    ""
    ╷
    │ Expect.equal
    ╵
    "\t"


Given "\n"

    ""
    ╷
    │ Expect.equal
    ╵
    "\n"



TEST RUN FAILED

Duration: 767 ms
Passed:   80
Failed:   2
```

**Comment by lorenzo** [comment]
Do you think the failing tests have to do with an updated version of elm-test? Tests where passing in the commit right before

**Comment by prikhi** [comment]
The travis script hardcodes elm-test to `0.18.6` instead of `0.18.9`. 

I think the test failure is due to elm-test's dependencies changing. Testing locally w/ `0.18.6` worked for me until I wiped my `elm-stuff` dirs.
```
-- Passing Travis Test Deps
 ● elm-community/elm-test 4.1.0
 ● elm-community/lazy-list 1.0.0
 ● elm-community/shrink 2.0.0
 ● elm-lang/core 5.1.1
 ● elm-lang/lazy 2.0.0
 ● mgold/elm-random-pcg 5.0.0

-- Failing Travis Test Deps
 ● eeue56/elm-lazy 1.0.0
 ● eeue56/elm-lazy-list 1.0.0
 ● eeue56/elm-shrink 1.0.0
 ● elm-community/elm-test 4.2.0
 ● elm-community/lazy-list 1.0.0
 ● elm-community/shrink 2.0.0
 ● elm-lang/core 5.1.1
 ● elm-lang/html 2.0.0
 ● elm-lang/lazy 2.0.0
 ● elm-lang/virtual-dom 2.0.4
 ● mgold/elm-random-pcg
```

Should probably change the travis script to install the `elm-test` version specified in `package.json` & run `sysconfcpus -n 2 npm run test` instead.

**Comment by sporto** [comment]
This is a good reason to have a package.json and elm test locally instead of relying on a global version.

**Comment by sporto** [comment]
I think that the travis setup should do `npm i` and the `npm run test`. Not install any version of elm-test globally.

**Comment by prikhi** [comment]
> This is a good reason to have a package.json and elm test locally instead of relying on a global version.

I agree, I was trying to say that the failing tests are due to newer versions of `elm-tests` elm dependencies, not the npm dependency(passing tests install `elm-test 4.1` while failing ones install `elm-test 4.2`).

> I think that the travis setup should do npm i and the npm run test. Not install any version of elm-test globally.

Yeah, this is what I meant but it should be `sysconfcpus -n 2 npm run test` or travis will time out while waiting for compilation.

**Comment by sporto** [comment]
Ok, it seems that in order to proceed we need to:

- Merge this failing branch
- Change travis config to install elm test locally
- Fix the test

Correct?

**Comment by jaapz** [comment]
Looks right to me, I'll get to it now

**Comment by jaapz** [comment]
By the way, I'm not really happy with the sysconfcpu setup we have now in travis, there's just a lot going on for a bit of speed gain for builds that don't get run a lot anyway.

**Comment by jaapz** [comment]
I have merged this, updated the travis ci config in master, and started a PR fixing the failing tests in #26.

I'm still not able to reliably get the tests to run on my machine, but maybe that's just because of my wonky arch install... I keep getting errors about missing a libz library (which is installed).

**Comment by sporto** [comment]
Great, I will wait for the tests to be fixed to start on the thing I wanted to contribute https://github.com/elm-community/string-extra/issues/23

**Pull request merged**
