### PR TITLE
Update for Elm 0.19

### PR DESCRIPTION
**Pull request by xtian**

### CODE REVIEW

**Comment by xtian** [comment]
ping @Lorenzo @jaapz

**Comment by xtian** [comment]
I'm not sure where `import Shrink` is supposed to come from in the test files

**Comment by ianmackenzie** [comment]
@xtian that's from https://github.com/eeue56/elm-shrink which has not yet been updated to Elm 0.19. `elm-test` itself is currently using a local (internal) copy of the `Shrink` module from that package, but as I understand it the plan is to update `elm-shrink` to 0.19 and then switch `elm-test` back over to using the published package. (I ran into this issue myself since I also use the `Shrink` module in some of my code - I logged https://github.com/elm-explorations/test/issues/15.)

**Comment by jaapz** [comment]
Should we maybe wait with adding 0.19 support until elm-test and elm-shrink have their 0.19 versions ready?

**Comment by lorenzo** [comment]
Also we should take care of https://github.com/elm-community/string-extra/issues/27#issuecomment-388588172 before making any release for 0.19

**Comment by lorenzo** [comment]
I'm ok with merging without tests for the time being, but the problem with code points should be addressed first

**Comment by ianmackenzie** [comment]
@lorenzo I'm happy to make a PR for the code points issue if you'd like - it really should be as simple as changing the implementations to the one-liners I mentioned, but I guess the documentation will also need to be updated!

**Comment by lorenzo** [comment]
@ianmackenzie sure, I'll merge this now and wait for your PR before tagging a new version

**Pull request merged**
